### ISSUE TITLE
Typo of file name in tutorial

### ISSUE THREAD

**Issue by astonyao** [treyhuffine/graphql-react-typescript-spacex#2]
In [the tutorial](https://blog.logrocket.com/build-a-graphql-react-app-with-typescript/), it says:

>The final step is to refetch the data when the id changes. Inside the ***LaunchList/index.tsx*** file, we will use the useEffect

Where this should be inside ***LaunchProfile/index.tsx*** instead.

**Comment by treyhuffine** [comment]
Thank you! I haven't had edit access to the story until, and this will be updated in the revision
